// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdBNONrJib7HUe9tDm_VAEEbFEyoW-D3w',
    appId: '1:538290085356:web:6355e0e56f75473da1b4c9',
    messagingSenderId: '538290085356',
    projectId: 'todo-app-r5',
    authDomain: 'todo-app-r5.firebaseapp.com',
    storageBucket: 'todo-app-r5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8p5UggruBwnfh8QnltIAKvAIuZI9hgYE',
    appId: '1:538290085356:android:3396eb186a76d758a1b4c9',
    messagingSenderId: '538290085356',
    projectId: 'todo-app-r5',
    storageBucket: 'todo-app-r5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ04XLRpOKlaRyQXoiZeuNHSINunUyVwI',
    appId: '1:538290085356:ios:6b155bcb10c24b87a1b4c9',
    messagingSenderId: '538290085356',
    projectId: 'todo-app-r5',
    storageBucket: 'todo-app-r5.appspot.com',
    iosBundleId: 'com.example.todoR5App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ04XLRpOKlaRyQXoiZeuNHSINunUyVwI',
    appId: '1:538290085356:ios:6b155bcb10c24b87a1b4c9',
    messagingSenderId: '538290085356',
    projectId: 'todo-app-r5',
    storageBucket: 'todo-app-r5.appspot.com',
    iosBundleId: 'com.example.todoR5App',
  );
}
